### ISSUE TITLE
Problem with require order in lib/ruby_ucp.rb

### ISSUE THREAD

**Issue by jeiler** [bitcoder/ruby_ucp#2]
The order in which files are "required" by ruby_ucp.rb is system dependent. On my system the files where not included in the correct order causing "NameError: uninitialized constant Ucp::Util::PackedMsg".

Implementing the following fixed order seems to resolve the issue:

require "ucp/base.rb"
require "ucp/pdu/base.rb"
require "ucp/pdu/ucpmessage.rb"
require "ucp/pdu/ucp_operation.rb"
require "ucp/pdu/ucp_result.rb"
require "ucp/pdu/ucp01.rb"
require "ucp/pdu/ucp01_operation.rb"
require "ucp/pdu/ucp01_result.rb"
require "ucp/pdu/ucp30.rb"
require "ucp/pdu/ucp30_operation.rb"
require "ucp/pdu/ucp30_result.rb"
require "ucp/pdu/ucp31.rb"
require "ucp/pdu/ucp31_operation.rb"
require "ucp/pdu/ucp31_result.rb"
require "ucp/pdu/ucp5x.rb"
require "ucp/pdu/ucp51_result.rb"
require "ucp/pdu/ucp51_operation.rb"
require "ucp/pdu/ucp52_operation.rb"
require "ucp/pdu/ucp52_result.rb"
require "ucp/pdu/ucp53_operation.rb"
require "ucp/pdu/ucp53_result.rb"
require "ucp/pdu/ucp54_operation.rb"
require "ucp/pdu/ucp54_result.rb"
require "ucp/pdu/ucp55_operation.rb"
require "ucp/pdu/ucp55_result.rb"
require "ucp/pdu/ucp56_operation.rb"
require "ucp/pdu/ucp56_result.rb"
require "ucp/pdu/ucp57_operation.rb"
require "ucp/pdu/ucp57_result.rb"
require "ucp/pdu/ucp58_operation.rb"
require "ucp/pdu/ucp58_result.rb"
require "ucp/pdu/ucp60.rb"
require "ucp/pdu/ucp60_operation.rb"
require "ucp/pdu/ucp60_result.rb"
require "ucp/pdu/ucp61.rb"
require "ucp/pdu/ucp61_result.rb"
require "ucp/pdu/ucp61_operation.rb"
require "ucp/util/base.rb"
require "ucp/util/packed_msg.rb"
require "ucp/util/gsm_packed_msg.rb"
require "ucp/util/ucp_client.rb"
require "ucp/util/sms_request.rb"
require "ucp/util/ucp.rb"
require "ucp/util/ucp_server.rb"
require "ucp/util/ucs2_packed_msg.rb"

**Comment by bitcoder** [comment]
hmm I guess you're right.
I think the problem is due to this code:

# Load all YCP PDUs

Dir.glob(File.join(File.dirname(**FILE**), 'ucp', 'pdu', '*.rb')) do |f|
  require f  unless f.match('ucpmessage.rb$')
end

# Load all auxiliary classes

Dir.glob(File.join(File.dirname(**FILE**), 'ucp', 'util', '*.rb')) do |f|
  require f  unless f.match('base.rb$')
end

Which does not guarantee the order of "importing" the classes.
Although I'd rather prefer another shorter/cleaner approach, I think your fix is correct so I'm going to import it to the code. If any problem arises, I'll have to look back into this.
Thanks!
